//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCEventCalendar
{
    using System;
    using System.Collections.Generic;
    
    public partial class Login
    {
        public long id { get; set; }
        public string user { get; set; }
        public string password { get; set; }
        public Nullable<long> IdUser { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
